### ISSUE TITLE
Move "set container driver" content to "configure Vamp"

### ISSUE THREAD

**Issue by olafmol** [magneticio/revamp.io#173]
as we have installation instructions for all supported schedulers, and we have configure Vamp, we can move the set container driver content to A) specific Docker installation submenu item B) the rest to configure Vamp

**Comment by gggina** [comment]
The only content for the Docker page was the Vamp container driver configuration details, so that page was removed.
I can add all the container driver configuration details to configure Vamp, but that will make the page quite long (the current site puts 'container driver configuration' on a separate page http://vamp.io/documentation/installation/container_drivers/).
