### ISSUE TITLE
Missing logos in Firefox for "Vamp works with"

### ISSUE THREAD

**Issue by dragoslav** [magneticio/revamp.io#177]
Chrome displays them.
![screen shot 2016-10-12 at 18 05 09](https://cloud.githubusercontent.com/assets/7957524/19317817/9133347e-90a6-11e6-8b7c-35b96f43309e.png)

**Comment by olafmol** [comment]
can confirm this happens in FF both on the local and github version. It's specific to FF, the logos show up in safari and chrome.

**Comment by olafmol** [comment]
in FF still no tech logos

**Comment by brniamut** [comment]
![screenshot 2016-10-13 11 29 31](https://cloud.githubusercontent.com/assets/2960616/19343926/83e49622-9138-11e6-8bc9-c86e1f3b9d79.png)

Working in firefox also showing on gina's computer. Please try to empty your cahce and do a hard reload. Try to see if the problem is local before reopening the issue.

**Comment by dragoslav** [comment]
@brniamut: "Try to see if the problem is local before reopening the issue", at 13 Oct 2016, 11:33 GMT+2

Just for the record:
- issue created on 12 Oct 2016, 18:07 GMT+2, last commit at that time https://github.com/magneticio/revamp.io/commit/c950b3936205f5c4eb1582861ec283ffea8537c3 - it does not work
- your next commit https://github.com/magneticio/revamp.io/commit/c2d21113d4e32b258b7c96ea0b155a6cb72bcaa2 fixes this #177 (`Fixes #177` commit message) at 13 Oct 2016, 11:17 GMT+2 (16 minutes after your comment)

**Comment by olafmol** [comment]
i can confirm the issue is now fixed in FF

**Comment by brniamut** [comment]
@dragoslav My comment/commit which fixed this was at: 11.18. The issue was reopened at 11:25. It was fixed by then. Let's talk about this when everybody is back at the office because, github is not the place to have this discussion. Taking full responsibility for starting the discussion because of my last comment, shouldn't do that.
